# Generated by Django 5.2.3 on 2025-06-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='firstname', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='secondname', max_length=250),
        ),
    ]
