# Generated by Django 5.2.3 on 2025-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug_user',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
