# Generated by Django 5.2.3 on 2025-07-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_slug_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug_user',
            new_name='username',
        ),
    ]
